/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialMedicalResearchInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeResearcher"
      | "authorizedResearchers"
      | "completeStudyManually"
      | "computeAggregatedResults"
      | "confidentialProtocolId"
      | "createMedicalStudy"
      | "currentStudyId"
      | "getCurrentStudyId"
      | "getPatientSubmissionStatus"
      | "getStudyInfo"
      | "getStudyParticipants"
      | "isPatientVerified"
      | "isResearcherAuthorized"
      | "lastStudyTime"
      | "medicalStudies"
      | "patientSubmissions"
      | "publishResults"
      | "researchCoordinator"
      | "submitPatientData"
      | "verifiedPatients"
      | "verifyPatient"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PatientDataSubmitted"
      | "PatientVerified"
      | "ResearcherAuthorized"
      | "ResultsPublished"
      | "StudyCompleted"
      | "StudyCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeResearcher",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedResearchers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeStudyManually",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "computeAggregatedResults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createMedicalStudy",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentStudyId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentStudyId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientSubmissionStatus",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudyInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudyParticipants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPatientVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isResearcherAuthorized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastStudyTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "medicalStudies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "patientSubmissions",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "publishResults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "researchCoordinator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitPatientData",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedPatients",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyPatient",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeResearcher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedResearchers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeStudyManually",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeAggregatedResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMedicalStudy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentStudyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentStudyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientSubmissionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudyParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPatientVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isResearcherAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastStudyTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "medicalStudies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "patientSubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "researchCoordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPatientData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedPatients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyPatient",
    data: BytesLike
  ): Result;
}

export namespace PatientDataSubmittedEvent {
  export type InputTuple = [patient: AddressLike, studyId: BigNumberish];
  export type OutputTuple = [patient: string, studyId: bigint];
  export interface OutputObject {
    patient: string;
    studyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatientVerifiedEvent {
  export type InputTuple = [patient: AddressLike];
  export type OutputTuple = [patient: string];
  export interface OutputObject {
    patient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResearcherAuthorizedEvent {
  export type InputTuple = [researcher: AddressLike];
  export type OutputTuple = [researcher: string];
  export interface OutputObject {
    researcher: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultsPublishedEvent {
  export type InputTuple = [studyId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [studyId: bigint, timestamp: bigint];
  export interface OutputObject {
    studyId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StudyCompletedEvent {
  export type InputTuple = [
    studyId: BigNumberish,
    participantCount: BigNumberish
  ];
  export type OutputTuple = [studyId: bigint, participantCount: bigint];
  export interface OutputObject {
    studyId: bigint;
    participantCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StudyCreatedEvent {
  export type InputTuple = [
    studyId: BigNumberish,
    title: string,
    startTime: BigNumberish
  ];
  export type OutputTuple = [studyId: bigint, title: string, startTime: bigint];
  export interface OutputObject {
    studyId: bigint;
    title: string;
    startTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialMedicalResearch extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialMedicalResearch;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialMedicalResearchInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeResearcher: TypedContractMethod<
    [_researcher: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedResearchers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  completeStudyManually: TypedContractMethod<
    [_studyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  computeAggregatedResults: TypedContractMethod<
    [_studyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createMedicalStudy: TypedContractMethod<
    [_title: string, _description: string, _targetParticipants: BigNumberish],
    [void],
    "nonpayable"
  >;

  currentStudyId: TypedContractMethod<[], [bigint], "view">;

  getCurrentStudyId: TypedContractMethod<[], [bigint], "view">;

  getPatientSubmissionStatus: TypedContractMethod<
    [_studyId: BigNumberish, _patient: AddressLike],
    [[boolean, bigint] & { hasSubmitted: boolean; submissionTime: bigint }],
    "view"
  >;

  getStudyInfo: TypedContractMethod<
    [_studyId: BigNumberish],
    [
      [string, string, boolean, boolean, boolean, bigint, bigint] & {
        title: string;
        description: string;
        dataCollectionActive: boolean;
        studyCompleted: boolean;
        resultsPublished: boolean;
        participantCount: bigint;
        targetParticipants: bigint;
      }
    ],
    "view"
  >;

  getStudyParticipants: TypedContractMethod<
    [_studyId: BigNumberish],
    [string[]],
    "view"
  >;

  isPatientVerified: TypedContractMethod<
    [_patient: AddressLike],
    [boolean],
    "view"
  >;

  isResearcherAuthorized: TypedContractMethod<
    [_researcher: AddressLike],
    [boolean],
    "view"
  >;

  lastStudyTime: TypedContractMethod<[], [bigint], "view">;

  medicalStudies: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        string,
        boolean
      ] & {
        studyId: bigint;
        studyTitle: string;
        description: string;
        dataCollectionActive: boolean;
        studyCompleted: boolean;
        resultsPublished: boolean;
        startTime: bigint;
        endTime: bigint;
        targetParticipants: bigint;
        aggregatedResults: string;
        hasAggregatedData: boolean;
      }
    ],
    "view"
  >;

  patientSubmissions: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, string, string, boolean, bigint, string] & {
        encryptedAge: string;
        encryptedSymptomScore: string;
        encryptedTreatmentResponse: string;
        hasSubmitted: boolean;
        submissionTime: bigint;
        patientAddress: string;
      }
    ],
    "view"
  >;

  publishResults: TypedContractMethod<
    [_studyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  researchCoordinator: TypedContractMethod<[], [string], "view">;

  submitPatientData: TypedContractMethod<
    [
      _studyId: BigNumberish,
      _age: BigNumberish,
      _symptomScore: BigNumberish,
      _treatmentResponse: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  verifiedPatients: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  verifyPatient: TypedContractMethod<
    [_patient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeResearcher"
  ): TypedContractMethod<[_researcher: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedResearchers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "completeStudyManually"
  ): TypedContractMethod<[_studyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "computeAggregatedResults"
  ): TypedContractMethod<[_studyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createMedicalStudy"
  ): TypedContractMethod<
    [_title: string, _description: string, _targetParticipants: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentStudyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentStudyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPatientSubmissionStatus"
  ): TypedContractMethod<
    [_studyId: BigNumberish, _patient: AddressLike],
    [[boolean, bigint] & { hasSubmitted: boolean; submissionTime: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStudyInfo"
  ): TypedContractMethod<
    [_studyId: BigNumberish],
    [
      [string, string, boolean, boolean, boolean, bigint, bigint] & {
        title: string;
        description: string;
        dataCollectionActive: boolean;
        studyCompleted: boolean;
        resultsPublished: boolean;
        participantCount: bigint;
        targetParticipants: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStudyParticipants"
  ): TypedContractMethod<[_studyId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "isPatientVerified"
  ): TypedContractMethod<[_patient: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isResearcherAuthorized"
  ): TypedContractMethod<[_researcher: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastStudyTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "medicalStudies"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        string,
        boolean
      ] & {
        studyId: bigint;
        studyTitle: string;
        description: string;
        dataCollectionActive: boolean;
        studyCompleted: boolean;
        resultsPublished: boolean;
        startTime: bigint;
        endTime: bigint;
        targetParticipants: bigint;
        aggregatedResults: string;
        hasAggregatedData: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "patientSubmissions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, string, string, boolean, bigint, string] & {
        encryptedAge: string;
        encryptedSymptomScore: string;
        encryptedTreatmentResponse: string;
        hasSubmitted: boolean;
        submissionTime: bigint;
        patientAddress: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "publishResults"
  ): TypedContractMethod<[_studyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "researchCoordinator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitPatientData"
  ): TypedContractMethod<
    [
      _studyId: BigNumberish,
      _age: BigNumberish,
      _symptomScore: BigNumberish,
      _treatmentResponse: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifiedPatients"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyPatient"
  ): TypedContractMethod<[_patient: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "PatientDataSubmitted"
  ): TypedContractEvent<
    PatientDataSubmittedEvent.InputTuple,
    PatientDataSubmittedEvent.OutputTuple,
    PatientDataSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "PatientVerified"
  ): TypedContractEvent<
    PatientVerifiedEvent.InputTuple,
    PatientVerifiedEvent.OutputTuple,
    PatientVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "ResearcherAuthorized"
  ): TypedContractEvent<
    ResearcherAuthorizedEvent.InputTuple,
    ResearcherAuthorizedEvent.OutputTuple,
    ResearcherAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "ResultsPublished"
  ): TypedContractEvent<
    ResultsPublishedEvent.InputTuple,
    ResultsPublishedEvent.OutputTuple,
    ResultsPublishedEvent.OutputObject
  >;
  getEvent(
    key: "StudyCompleted"
  ): TypedContractEvent<
    StudyCompletedEvent.InputTuple,
    StudyCompletedEvent.OutputTuple,
    StudyCompletedEvent.OutputObject
  >;
  getEvent(
    key: "StudyCreated"
  ): TypedContractEvent<
    StudyCreatedEvent.InputTuple,
    StudyCreatedEvent.OutputTuple,
    StudyCreatedEvent.OutputObject
  >;

  filters: {
    "PatientDataSubmitted(address,uint32)": TypedContractEvent<
      PatientDataSubmittedEvent.InputTuple,
      PatientDataSubmittedEvent.OutputTuple,
      PatientDataSubmittedEvent.OutputObject
    >;
    PatientDataSubmitted: TypedContractEvent<
      PatientDataSubmittedEvent.InputTuple,
      PatientDataSubmittedEvent.OutputTuple,
      PatientDataSubmittedEvent.OutputObject
    >;

    "PatientVerified(address)": TypedContractEvent<
      PatientVerifiedEvent.InputTuple,
      PatientVerifiedEvent.OutputTuple,
      PatientVerifiedEvent.OutputObject
    >;
    PatientVerified: TypedContractEvent<
      PatientVerifiedEvent.InputTuple,
      PatientVerifiedEvent.OutputTuple,
      PatientVerifiedEvent.OutputObject
    >;

    "ResearcherAuthorized(address)": TypedContractEvent<
      ResearcherAuthorizedEvent.InputTuple,
      ResearcherAuthorizedEvent.OutputTuple,
      ResearcherAuthorizedEvent.OutputObject
    >;
    ResearcherAuthorized: TypedContractEvent<
      ResearcherAuthorizedEvent.InputTuple,
      ResearcherAuthorizedEvent.OutputTuple,
      ResearcherAuthorizedEvent.OutputObject
    >;

    "ResultsPublished(uint32,uint256)": TypedContractEvent<
      ResultsPublishedEvent.InputTuple,
      ResultsPublishedEvent.OutputTuple,
      ResultsPublishedEvent.OutputObject
    >;
    ResultsPublished: TypedContractEvent<
      ResultsPublishedEvent.InputTuple,
      ResultsPublishedEvent.OutputTuple,
      ResultsPublishedEvent.OutputObject
    >;

    "StudyCompleted(uint32,uint256)": TypedContractEvent<
      StudyCompletedEvent.InputTuple,
      StudyCompletedEvent.OutputTuple,
      StudyCompletedEvent.OutputObject
    >;
    StudyCompleted: TypedContractEvent<
      StudyCompletedEvent.InputTuple,
      StudyCompletedEvent.OutputTuple,
      StudyCompletedEvent.OutputObject
    >;

    "StudyCreated(uint32,string,uint256)": TypedContractEvent<
      StudyCreatedEvent.InputTuple,
      StudyCreatedEvent.OutputTuple,
      StudyCreatedEvent.OutputObject
    >;
    StudyCreated: TypedContractEvent<
      StudyCreatedEvent.InputTuple,
      StudyCreatedEvent.OutputTuple,
      StudyCreatedEvent.OutputObject
    >;
  };
}
